<<<<<<< HEAD
# application-sqlite.yaml
spring:
=======
spring:
  config.activate.on-profile: sqlite
  web.resources.static-locations: "file:./app"
>>>>>>> flp
  datasource:
    url: jdbc:sqlite:../db/sqlite.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0
  sql.init:
    mode: never
cds:
  datasource:
    auto-config:
      enabled: false
  sql.supportedLocales: "*"
  odata-v4:
    endpoint.path: "/api"
